### ISSUE TITLE
Nested types compatibility when using Prisma + MongoDB

### ISSUE THREAD

**Issue by NicolasRibbon** [chrishoermann/zod-prisma-types#54] opened 2023-01-11 14:52 UTC
First of all, thanks for working on this tool and taking over from the other, seemingly unmaintained project.

We are using Prisma with MongoDB at work. I had a quick play around, and it seems types are not being generated when creating the validators. Is that right?

i.e. 

```
model Post {
  id          String       @id @default(auto()) @map("_id") @db.ObjectId
  title       String       @default("")
  data      PostData
}

type PostData {
    something         String
    somethingElse  Number
}
```

Will generate a Post validator without the `data` field. That's the only thing that's preventing us from using this library basically. Is that something that's know/in the works? Let me know if I can help with that!

**Comment by chrishoermann** [comment] 2023-01-12 21:26
Hey @NicolasRibbon 

currently no relations are created for model schemas because I first intended model schemas to be used for validating input types in libraries like react-hook-form and I assumed that only the scalar and enum values would be needed for that.

What would be your usecase for the relations? maybe the types you need are already created as `inputTypes`, `argTypes`, etc. like `PostCreateInputSchema`, `PostCreateArgsSchema` and so on?

A downside of added relations in the model schema is that they can  become recursive (at least if this behaviour is needed?). In this case the `z.ZodType<some typescript type>` needs to be added and then the schema looses the ability to use some methods like `pick`, `omit`, etc. Because of this and for flexibility reasons I would just add a separate schema like `MyModelWithReltaionsSchema` that extends the base model schema and adds relations. 

If this feature is definitly needed I'll look into this in the next few days but currently I want to focus my efforts on adding the option to generate multiple files instead of a single `index.ts` (see #48) so if you need this feature asap  feel free to dig into it and sumbit a PR.

I already started tooling around in the latest commit on master - the magic happens in `packages/generator/src/functions/getModelStatements.ts`. The generator option `createModelRelations` is already implemented.

**Comment by NicolasRibbon** [comment] 2023-01-13 12:09
Hey Chris,

Thanks a lot for taking the time to reply. That is exactly my use case, validating a form, although with Formik in my case, but same thing.

Sorry for not explaining myself better in the first message. I think there's a misunderstanding. `types` within the Prisma schema are not used as relationships. They are literally objects within a document in MongoDB.

For example:

```js
{
    id: "5f9d98f6c2bdb3f5c4e4a5b7",
    title: "Welcome to my Blog",
    data: {
      content: "Hello there",
      views: 123
   }
}
```

This document in Prisma would be represented like I've shown in the first example. Data is not optional and it is not a relation, it will be mandatory data when creating a `Post`, so it makes sense for it to be part of the schema. I hope that makes it clearer!

**Comment by chrishoermann** [comment] 2023-01-16 18:38
Ah now I understand. I haven't worked with mongoDb so far so I didn't get the reference in your first example. But now I know what I'm looking for. I try to look into this in the next few days and report back when I found the types that need to be generated in the depth of the `prisma dmmf`.

**Comment by Nikola-Milovic** [comment] 2023-01-25 18:59
Experiencing the same issue, but some of the `type`'s are getting generated, some not

![image](https://user-images.githubusercontent.com/50072027/214657059-59298bbc-d354-47ed-8482-f4c4480d6a50.png)

Both `CampaignAudience` and `CampaignAudienceAge` are types

```
type CampaignAudience {
    age        CampaignAudienceAge?
    gender     String
}

type CampaignAudienceAge {
    maxAge Int
    minAge Int
}
```

Also, a blocker for me to migrate, I tried looking into the source to look into it myself but not much luck, not familiar with generators. In general, the types should practically be like models, export their schema, and nest them in other schemas where necessary

**Comment by chrishoermann** [comment] 2023-01-28 21:41
@Nikola-Milovic, @NicolasRibbon I just released version `2.0.0-beta.1` that should fix the basic issue with mongo db types. The only thing i need to fiqure out is how to generate the correct `include` types. Are they even supported for types in mongoDb? Could you please test the implementation and see if the issues are also fixed on your end.
The beta docs can be found [here](https://github.com/chrishoermann/zod-prisma-types/tree/dev). 

npm:

```bash
npm install zod-prisma-types@2.0.0-beta.1
```

yarn:

```bash
yarn add zod-prisma-types@2.0.0-beta.1
```

pnpm:

```bash
pnpm add zod-prisma-types@2.0.0-beta.1
```

**Comment by Nikola-Milovic** [comment] 2023-01-29 15:13
@chrishoermann So just downloading the beta and trying it out, it seems everything is fixed, the only bug I found is the following

```
export const ModeratedContentIncludeSchema: z.ZodType<PrismaClient.Prisma.ModeratedContentInclude> = z.object({
  files: z.union([z.boolean(),z.lazy(() => ModeratedContentFileFindManyArgsSchema)]).optional(),
}).strict()

export const ModeratedContentArgsSchema: z.ZodType<PrismaClient.Prisma.ModeratedContentArgs> = z.object({
  select: z.lazy(() => ModeratedContentSelectSchema).optional(),
  include: z.lazy(() => ModeratedContentIncludeSchema).optional(),
}).strict();

export const ModeratedContentSelectSchema: z.ZodType<PrismaClient.Prisma.ModeratedContentSelect> = z.object({
  id: z.boolean().optional(),
  v: z.boolean().optional(),
  files: z.union([z.boolean(),z.lazy(() => ModeratedContentFileFindManyArgsSchema)]).optional(),
}).strict()
```
And these are the errors

```
apps/backend/src/generated/index.ts|680 col 44| Cannot find name 'ModeratedContentFileFindManyArgsSchema'. Did you mean 'ModeratedContentFindManyArgsSchema'?
apps/backend/src/generated/index.ts|694 col 44| Cannot find name 'ModeratedContentFileFindManyArgsSchema'. Did you mean 'ModeratedContentFindManyArgsSchema'?
```

`ModeratedContentFileFindManyArgsSchema` is nowhere to be found, but other fields for the `ModeratedContentFile` are generated without any issues.

This is the schema I am using

```
type ModeratedContentFile {
    mimetype String
    url      String
}

model ModeratedContent {
    id            String                 @id @map("_id")
    v             Int                    @map("__v")
    files         ModeratedContentFile[]
}
```


The issue is in the array, I am 99% sure. So to replicate this, have an array of a type and it's not gonna have the `FindManyArgs` schema present. Which will cause this error


I'll have to test the other generator options as well, but its working fine for me

---

> The only thing i need to fiqure out is how to generate the correct include types. Are they even supported for types in mongoDb?

Can you elaborate on what you mean?

--- 

One thing that I am noticing, maybe the thing you referred to in the `include` types question, but the schemas aren't connected, meaning if we have an embedded schema with a  type

```
model Account {
    id                 String           @id @map("_id")
    v                  Int              @map("__v")
    profile           Profile
}

type Profile {
    address       Address
}
```

Then the output schema will not have the `profile` field that's `ProfileSchema`

**Comment by chrishoermann** [comment] 2023-01-31 15:52
@Nikola-Milovic in the latest official version the `include` bug should now be fixed.

**Comment by Nikola-Milovic** [comment] 2023-01-31 17:07
@chrishoermann It now works for an array of types, it doesn't have any errors! Thanks Chris 

Not sure about the `include` bug that you're referring to.

The models are still missing `type` fields, and that is as far as I know the only issue I am having.

```
type BusinessProfile {
    address       BusinessAddress
}

model Business {
    id                 String           @id @map("_id")
    v                  Int              @map("__v")
    createdAt          Float
    email              String           @unique(map: "email_1")
    profile            BusinessProfile?
    settings           BusinessSettings
}
```

And this gets generated, note the settings and the profile are missing

```
export const BusinessSchema = z.object({
  id: z.string(),
  v: z.number().int(),
  createdAt: z.number(),
  email: z.string(),
})
```

**Comment by chrishoermann** [comment] 2023-01-31 18:09
@Nikola-Milovic have you used the option `createRelationValueTypes` like mentioned in the [docs](https://github.com/chrishoermann/zod-prisma-types#createrelationvaluestypes)?

**Comment by Nikola-Milovic** [comment] 2023-01-31 18:49
That was it, works flawlessly

**Comment by chrishoermann** [comment] 2023-01-31 18:59
Glad to hear that, clossing this issue now as it seems to be fixed.

**Closed by chrishoermann** 2023-01-31 18:59 UTC
